name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          PATH="$PATH:./node_modules/.bin/"
          npm install
          npm install spago@next purescript
          npx playwright install --with-deps chromium
          spago test
